import f1 from "../Feeds/flg/z1.jpg";
import model from "../Feeds/flg/z10.jpg";
import model2 from "../Feeds/flg/z3.jpg";
import model3 from "../Feeds/flg/z4.jpg";
import m1 from "../Feeds/flg/z5.jpg";
import m2 from "../Feeds/flg/z6.jpg";
import m3 from "../Feeds/flg/z7.jpg";
import m4 from "../Feeds/flg/z8.jpg";
import m5 from "../Feeds/flg/z9.jpg";
import m6 from "../Feeds/flg/z10.jpg";
import m7 from "../Feeds/flg/z11.jpg";
import m8 from "../Feeds/flg/z12.jpg";
import m9 from "../Feeds/flg/z13.jpg";
import m10 from "../Feeds/flg/z14.jpg";
import m11 from "../Feeds/flg/z15.jpg";


// Use more diverse images
const instagramFeed = [
  {
    id: 1,
    username: "food.explorer",
    time: "1h",
    profileImg: f1,
    postImg: model,
    mutualFrndImg1: "https://source.unsplash.com/random/?boy1",
    mutualFrndImg2: "https://source.unsplash.com/random/?girl1",
    likeCount: 850,
    caption: "Exploring the best food around the world.",
    commentCount: "100",
  },
  {
    id: 2,
    username: "nature.lover",
    time: "2h",
    profileImg: m2,
    postImg: m5,
    mutualFrndImg1: "https://source.unsplash.com/random/?girl2",
    mutualFrndImg2: "https://source.unsplash.com/random/?boy2",
    likeCount: 208,
    caption: "Loving the beauty of nature.",
    commentCount: "78",
  },
  {
    id: 3,
    username: "reelsofworld",
    time: "3h",
    profileImg: m10,
    postImg: m8,
    mutualFrndImg1: "https://source.unsplash.com/random/?girl3",
    mutualFrndImg2: "https://source.unsplash.com/random/?boy3",
    likeCount: 420,
    caption: "Sharing the best reels of the world!",
    commentCount: "150",
  },
  {
    id: 4,
    username: "carlover",
    time: "4h",
    profileImg: m3,
    postImg: m11,
    mutualFrndImg1: "https://source.unsplash.com/random/?boy4",
    mutualFrndImg2: "https://source.unsplash.com/random/?girl4",
    likeCount: 523,
    caption: "Dreaming of the finest cars.",
    commentCount: "95",
  },
  {
    id: 5,
    username: "godness",
    time: "5h",
    profileImg: model3,
    postImg: m2,
    mutualFrndImg1: "https://source.unsplash.com/random/?girl5",
    mutualFrndImg2: "https://source.unsplash.com/random/?boy5",
    likeCount: 634,
    caption: "Elegance is beauty.",
    commentCount: "110",
  },
  {
    id: 6,
    username: "wanderlust",
    time: "6h",
    profileImg: m4,
    postImg: m10,
    mutualFrndImg1: "https://source.unsplash.com/random/?girl6",
    mutualFrndImg2: "https://source.unsplash.com/random/?boy6",
    likeCount: 754,
    caption: "Traveling the world, one step at a time.",
    commentCount: "85",
  },
  {
    id: 7,
    username: "fitnfun",
    time: "7h",
    profileImg: m5,
    postImg: m2,
    mutualFrndImg1: "https://source.unsplash.com/random/?boy7",
    mutualFrndImg2: "https://source.unsplash.com/random/?girl7",
    likeCount: 890,
    caption: "Living the fit life!",
    commentCount: "150",
  },
  {
    id: 8,
    username: "techguru",
    time: "8h",
    profileImg: model,
    postImg: m7,
    mutualFrndImg1: "https://source.unsplash.com/random/?girl8",
    mutualFrndImg2: "https://source.unsplash.com/random/?boy8",
    likeCount: 450,
    caption: "Stay ahead with the latest tech.",
    commentCount: "230",
  },
  {
    id: 9,
    username: "styleicon",
    time: "9h",
    profileImg: m6,
    postImg: m1,
    mutualFrndImg1: "https://source.unsplash.com/random/?girl9",
    mutualFrndImg2: "https://source.unsplash.com/random/?boy9",
    likeCount: 324,
    caption: "Style is an attitude.",
    commentCount: "190",
  },
  {
    id: 10,
    username: "explorerlife",
    time: "10h",
    profileImg: f1,
    postImg: model2,
    mutualFrndImg1: "https://source.unsplash.com/random/?girl10",
    mutualFrndImg2: "https://source.unsplash.com/random/?boy10",
    likeCount: 780,
    caption: "Life is an adventure!",
    commentCount: "165",
  },
  {
    id: 11,
    username: "gamingmaster",
    time: "11h",
    profileImg: m3,
    postImg: m4,
    mutualFrndImg1: "https://source.unsplash.com/random/?boy11",
    mutualFrndImg2: "https://source.unsplash.com/random/?girl11",
    likeCount: 987,
    caption: "Level up your game!",
    commentCount: "210",
  },
  {
    id: 12,
    username: "photogenic",
    time: "12h",
    profileImg: m8,
    postImg: model3,
    mutualFrndImg1: "https://source.unsplash.com/random/?girl12",
    mutualFrndImg2: "https://source.unsplash.com/random/?boy12",
    likeCount: 410,
    caption: "Capturing moments one click at a time.",
    commentCount: "130",
  },
  {
    id: 13,
    username: "travelvibes",
    time: "13h",
    profileImg: m9,
    postImg: m7,
    mutualFrndImg1: "https://source.unsplash.com/random/?boy13",
    mutualFrndImg2: "https://source.unsplash.com/random/?girl13",
    likeCount: 565,
    caption: "Travel is the best therapy.",
    commentCount: "112",
  },
  {
    id: 14,
    username: "adventurefreak",
    time: "14h",
    profileImg: m10,
    postImg: f1,
    mutualFrndImg1: "https://source.unsplash.com/random/?girl14",
    mutualFrndImg2: "https://source.unsplash.com/random/?boy14",
    likeCount: 980,
    caption: "For the thrill seekers!",
    commentCount: "145",
  },
  {
    id: 15,
    username: "fashionqueen",
    time: "15h",
    profileImg: model2,
    postImg: m6,
    mutualFrndImg1: "https://source.unsplash.com/random/?girl15",
    mutualFrndImg2: "https://source.unsplash.com/random/?boy15",
    likeCount: 679,
    caption: "Fashion is my passion.",
    commentCount: "120",
  },
];

export default instagramFeed;
